using Entities.Concrete.Entities.PLC.Recipe;
using FluentValidation;


namespace Business.Validators.FluentValidators.PLC.Recipe
{
    public class PLCRecipeValidator : AbstractValidator<PLCRecipe>
    {
        public PLCRecipeValidator()
        {
            RuleFor(x => x.Id).NotEmpty();
            RuleFor(x => x.RecipeNumber).InclusiveBetween(int.MinValue, int.MaxValue);//TagName:RecipeNumber,TagValue:DB 96 DBW 40
            RuleFor(x => x.MaterialThickness).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_0,DisplayName: Material thickness [µm],TagName:MaterialThickness,TagValue:DB 91 DBW 36
            RuleFor(x => x.RewinderOneMaterialWidth).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_1 ,DisplayName:Material width rewinder [mm] ,TagName:Rew1MaterialWidth,TagValue: DB 91 DBW 310
            RuleFor(x => x.MachineSpeedSet).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_2 ,DisplayName: Set speed [m/min] ,TagName:MachineSpeedSet,TagValue: DB 91 DBW 2
            RuleFor(x => x.UnwinderOneDiameterSet).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_3 ,DisplayName:  Set diameter unwinder [mm] ,TagName:Unw1DiaSet,TagValue: DB 91 DBW 100
            RuleFor(x => x.RewinderOneDiameterSet).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_4 ,DisplayName: Set diameter rewinder 1 [mm],TagName:Rew1DiaSet,TagValue:  DB 91 DBW 300
            RuleFor(x => x.RewinderOneLengthSet).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_5 ,DisplayName: Set length rewinder 1  [m] Set diameter rewinder 1 [mm] ,TagName:Rew1LengthSet,TagValue:  DB 91 DBD 306
            RuleFor(x => x.RewinderOneTensionSetScaled).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_6 ,DisplayName:  Tension rewinder 1 [N/mm²] ,TagName:Rew1TensionSetScaled,TagValue:  DB 91 DBW 312
            RuleFor(x => x.RewinderOneTensionContactSetScaled).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_7 ,DisplayName: Tension contact roll rewinder 1  [N/mm²],TagName:Rew1TensionContSetScaled,TagValue:  DB 91 DBW 342
            RuleFor(x => x.RewinderOneTensionLaySetScaled).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_8  ,DisplayName:Tension layon roll rewinder 1 [N/mm²],TagName:Rew1TensionLaySetScaled,TagValue:  DB 91 DBW 372
            RuleFor(x => x.RewinderOnePressureContactBalance).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_10  ,DisplayName: Balance contact roll rewinder 1 [%],TagName:Rew1PresContBalance,TagValue:  DB 91 DBW 336
            RuleFor(x => x.RewinderOnePressureLaySetScaled).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_11  ,DisplayName:  Pressure layon roll rewinder 1 [N/mm],TagName:Rew1PresLaySetScaled,TagValue:  DB 91 DBW 352
            RuleFor(x => x.RewinderOnePressureLayBalance).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_12  ,DisplayName: Balance layon roll rewinder 1 [%],TagName:Rew1PresLayBalance,TagValue: DB 91 DBW 366
            RuleFor(x => x.RewinderTwoDiameterSet).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_13  ,DisplayName: Set diameter rewinder 2  [mm],TagName:Rew2DiaSet,TagValue:  DB 91 DBW 400
            RuleFor(x => x.RewinderTwoLengthSet).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_14  ,DisplayName: Set length rewinder 2 [m],TagName:Rew2LengthSet,TagValue: DB 91 DBD 406
            RuleFor(x => x.RewinderTwoTensionSetScaled).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_15  ,DisplayName: Tension rewinder 2 [N/mm²],TagName:Rew2TensionSetScaled,TagValue:  DB 91 DBW 412
            RuleFor(x => x.RewinderTwoTensionContactSetScaled).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_16  ,DisplayName:  Tension contact roll rewinder 2  [N/mm²],TagName:Rew2TensionContSetScaled,TagValue:   DB 91 DBW 442
            RuleFor(x => x.RewinderTwoTensionSupportSetScaled).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_17  ,DisplayName: Tension support roll rewinder 2  [N/mm²],TagName:Rew2TensionSupSetScaled,TagValue:  DB 91 DBW 472
            RuleFor(x => x.RewinderTwoPressureContactSetScaled).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_18  ,DisplayName: Pressure contact roll rewinder 2  [N/mm],TagName:Rew2PresContSetScaled,TagValue:  DB 91 DBW 422
            RuleFor(x => x.RewinderTwoPressureContactBalance).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_19  ,DisplayName: Balance pres. cont. roll rew. 2[%],TagName:Rew2PresContBalance,TagValue:  DB 91 DBW 436
            RuleFor(x => x.RewinderTwoPressureSupportSetScaled).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_20  ,DisplayName: Pressure support roll rewinder 2  [N/mm],TagName:Rew2PresSupSetScaled,TagValue:DB 91 DBW 452
            RuleFor(x => x.RewinderTwoPressureSupportBalance).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_21  ,DisplayName:Balance pres. sup. roll rew. 2 [%] ,TagName:Rew2PresSupBalance,TagValue: DB 91 DBW 466
            RuleFor(x => x.MachineTimeAcceleration).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_22  ,DisplayName: Acceleration time [s],TagName:MachineTimeAccel,TagValue:DB 91 DBW 8
            RuleFor(x => x.MachineTimeDecelarition).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_23  ,DisplayName:Deceleration time [s] ,TagName:MachineTimeDecel,TagValue:DB 91 DBW 10
            RuleFor(x => x.MachineTimeFastStop).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_24  ,DisplayName: Fast stop time [s] ,TagName:MachineTimeFastStop,TagValue:  DB 91 DBW 12
            RuleFor(x => x.TransportTensionSet).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_25  ,DisplayName: Set tension transport rolls [%] ,TagName:TransportTensionSet,TagValue:  DB 91 DBW 550
            RuleFor(x => x.MachineWeldingSpeedSet).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_26   ,DisplayName:Welding speed [mm/s],TagName:MachineWeldingSpeedSet,TagValue:  DB 91 DBW 80
            RuleFor(x => x.RewinderOneCharacteristicTensionOne).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_27  ,DisplayName:Tension characteristic rew.1 [di][%] ,TagName:Rew1CharacteristicTension_D01,TagValue: DB 93 DBW 2
            RuleFor(x => x.RewinderOneCharacteristicTensionTwo).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_28  ,DisplayName:Tension characteristic rew.1 [d2][%],TagName:Rew1CharacteristicTension_D02,TagValue:  DB 93 DBW 4
            RuleFor(x => x.RewinderOneCharacteristicTensionThree).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_29  ,DisplayName:Tension characteristic rew.1 [d3][%],TagName:Rew1CharacteristicTension_D03,TagValue:  DB 93 DBW 6
            RuleFor(x => x.RewinderOneCharacteristicTensionFour).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_30  ,DisplayName:Tension characteristic rew.1 [d4][%],TagName:Rew1CharacteristicTension_D04,TagValue:  DB 93 DBW 8
            RuleFor(x => x.RewinderOneCharacteristicTensionFive).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_31  ,DisplayName:Tension characteristic rew.1 [d5][%],TagName:Rew1CharacteristicTension_D05,TagValue:  DB 93 DBW 10
            RuleFor(x => x.RewinderOneCharacteristicTensionSix).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_32 ,DisplayName:Tension characteristic rew.1 [d6][%],TagName:Rew1CharacteristicTension_D06,TagValue:  DB 93 DBW 12
            RuleFor(x => x.RewinderOneCharacteristicTensionSeven).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_33  ,DisplayName:Tension characteristic rew.1 [d7][%],TagName:Rew1CharacteristicTension_D07,TagValue:  DB 93 DBW 14
            RuleFor(x => x.RewinderOneCharacteristicTensionEight).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_34  ,DisplayName:Tension characteristic rew.1 [d8][%],TagName:Rew1CharacteristicTension_D08,TagValue:  DB 93 DBW 16
            RuleFor(x => x.RewinderOneCharacteristicTensionNine).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_35 ,DisplayName:Tension characteristic rew.1 [d9][%],TagName:Rew1CharacteristicTension_D09,TagValue:  DB 93 DBW 18
            RuleFor(x => x.RewinderOneCharacteristicTensionTen).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_36 ,DisplayName:Tension characteristic rew.1 [d10][%],TagName:Rew1CharacteristicTension_D010,TagValue:  DB 93 DBW 20
            RuleFor(x => x.RewinderOneCharacteristicTensionSpeedInfluence).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_37 ,DisplayName:Tension characteristic rew.1 speed   [%],TagName:Rew1CharacteristicTensionSpeedInfluence,TagValue:    DB 93 DBW 0
            RuleFor(x => x.RewinderOneCharacteristicPressureContactOne).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_38 ,DisplayName: Pressure char. cont. roll rew.1 [d1][%],TagName:Rew1CharacteristicPressureContact_D01,TagValue: DB 93 DBW 122
            RuleFor(x => x.RewinderOneCharacteristicPressureContactTwo).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_39 ,DisplayName: Pressure char. cont. roll rew.1 [d2][%],TagName:Rew1CharacteristicPressureContact_D02,TagValue: DB 93 DBW 124
            RuleFor(x => x.RewinderOneCharacteristicPressureContactThree).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_40 ,DisplayName: Pressure char. cont. roll rew.1 [d3][%],TagName:Rew1CharacteristicPressureContact_D03,TagValue: DB 93 DBW 126
            RuleFor(x => x.RewinderOneCharacteristicPressureContactFour).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_41 ,DisplayName: Pressure char. cont. roll rew.1 [d4][%],TagName:Rew1CharacteristicPressureContact_D04,TagValue: DB 93 DBW 128
            RuleFor(x => x.RewinderOneCharacteristicPressureContactFive).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_42 ,DisplayName: Pressure char. cont. roll rew.1 [d5][%],TagName:Rew1CharacteristicPressureContact_D04,TagValue: DB 93 DBW 130
            RuleFor(x => x.RewinderOneCharacteristicPressureContactSix).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_43 ,DisplayName: Pressure char. cont. roll rew.1 [d6][%],TagName:Rew1CharacteristicPressureContact_D06,TagValue: DB 93 DBW 132
            RuleFor(x => x.RewinderOneCharacteristicPressureContactSeven).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_44 ,DisplayName: Pressure char. cont. roll rew.1 [d7][%],TagName:Rew1CharacteristicPressureContact_D07,TagValue: DB 93 DBW 134
            RuleFor(x => x.RewinderOneCharacteristicPressureContactEight).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_45 ,DisplayName: Pressure char. cont. roll rew.1 [d8][%],TagName:Rew1CharacteristicPressureContact_D08,TagValue: DB 93 DBW 136
            RuleFor(x => x.RewinderOneCharacteristicPressureContactNine).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_46 ,DisplayName: Pressure char. cont. roll rew.1 [d9][%],TagName:Rew1CharacteristicPressureContact_D09,TagValue: DB 93 DBW 138
            RuleFor(x => x.RewinderOneCharacteristicPressureContactTen).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_47 ,DisplayName: Pressure char. cont. roll rew.1 [d10][%],TagName:Rew1CharacteristicPressureContact_D10,TagValue: DB 93 DBW 140
            RuleFor(x => x.RewinderOneCharacteristicPressureContactSpeedInfluence).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_48 ,DisplayName:Pressure char. cont. roll rew.1 speed[%],TagName:Rew1CharacteristicPressureContactSpeedInfluence,TagValue:    DB 93 DBW 120
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnOne).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_49 ,DisplayName:Pressure char. layon roll rew.1 [d1][%],TagName:Rew1CharacteristicPressureLayOn_D01,TagValue:   DB 93 DBW 182
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnTwo).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_50 ,DisplayName:Pressure char. layon roll rew.1 [d2][%],TagName:Rew1CharacteristicPressureLayOn_D02,TagValue:   DB 93 DBW 184
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnThree).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_51 ,DisplayName:Pressure char. layon roll rew.1 [d3][%],TagName:Rew1CharacteristicPressureLayOn_D03,TagValue:   DB 93 DBW 186
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnFour).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_52 ,DisplayName:Pressure char. layon roll rew.1 [d4][%],TagName:Rew1CharacteristicPressureLayOn_D04,TagValue:   DB 93 DBW 188
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnFive).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_53 ,DisplayName:Pressure char. layon roll rew.1 [d5][%],TagName:Rew1CharacteristicPressureLayOn_D05,TagValue:   DB 93 DBW 190
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnSix).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_54 ,DisplayName:Pressure char. layon roll rew.1 [d6][%],TagName:Rew1CharacteristicPressureLayOn_D06,TagValue:   DB 93 DBW 192
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnSeven).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_55 ,DisplayName:Pressure char. layon roll rew.1 [d7][%],TagName:Rew1CharacteristicPressureLayOn_D07,TagValue:   DB 93 DBW 194
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnEight).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_56 ,DisplayName:Pressure char. layon roll rew.1 [d8][%],TagName:Rew1CharacteristicPressureLayOn_D08,TagValue:   DB 93 DBW 196
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnNine).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_57 ,DisplayName:Pressure char. layon roll rew.1 [d9][%],TagName:Rew1CharacteristicPressureLayOn_D09,TagValue:   DB 93 DBW 198
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnTen).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_58 ,DisplayName:Pressure char. layon roll rew.1 [d10][%],TagName:Rew1CharacteristicPressureLayOn_D010,TagValue:   DB 93 DBW 200
            RuleFor(x => x.RewinderOneCharacteristicPressureLayOnSpeedInfluence).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_59 ,DisplayName: Pressure char. layon roll rew.1 speed[%],TagName:Rew1CharacteristicPressureLayOnSpeedInfluence,TagValue:  DB 93 DBW 180
            RuleFor(x => x.RewinderTwoCharacteristicTensionOne).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_60 ,DisplayName:Tension characteristic rew.2 [d1][%],TagName:Rew2CharacteristicTension_D01,TagValue:   DB 93 DBW 32
            RuleFor(x => x.RewinderTwoCharacteristicTensionTwo).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_61 ,DisplayName:Tension characteristic rew.2 [d2][%],TagName:Rew2CharacteristicTension_D02,TagValue:   DB 93 DBW 34
            RuleFor(x => x.RewinderTwoCharacteristicTensionThree).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_62 ,DisplayName:Tension characteristic rew.2 [d3][%],TagName:Rew2CharacteristicTension_D03,TagValue:   DB 93 DBW 36
            RuleFor(x => x.RewinderTwoCharacteristicTensionFour).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_63 ,DisplayName:Tension characteristic rew.2 [d4][%],TagName:Rew2CharacteristicTension_D04,TagValue:   DB 93 DBW 38
            RuleFor(x => x.RewinderTwoCharacteristicTensionFive).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_64 ,DisplayName:Tension characteristic rew.2 [d5][%],TagName:Rew2CharacteristicTension_D05,TagValue:   DB 93 DBW 40
            RuleFor(x => x.RewinderTwoCharacteristicTensionSix).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_65 ,DisplayName:Tension characteristic rew.2 [d6][%],TagName:Rew2CharacteristicTension_D06,TagValue:   DB 93 DBW 42
            RuleFor(x => x.RewinderTwoCharacteristicTensionSeven).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_66 ,DisplayName:Tension characteristic rew.2 [d7][%],TagName:Rew2CharacteristicTension_D07,TagValue:   DB 93 DBW 44
            RuleFor(x => x.RewinderTwoCharacteristicTensionEight).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_67 ,DisplayName:Tension characteristic rew.2 [d8][%],TagName:Rew2CharacteristicTension_D08,TagValue:   DB 93 DBW 46
            RuleFor(x => x.RewinderTwoCharacteristicTensionNine).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_68 ,DisplayName:Tension characteristic rew.2 [d9][%],TagName:Rew2CharacteristicTension_D09,TagValue:   DB 93 DBW 48
            RuleFor(x => x.RewinderTwoCharacteristicTensionTen).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_69 ,DisplayName:Tension characteristic rew.2 [d10][%],TagName:Rew2CharacteristicTension_D010,TagValue:   DB 93 DBW 50
            RuleFor(x => x.RewinderTwoCharacteristicTensionSpeedInfluence).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_70 ,DisplayName:Tension characteristic rew.2 speed[%],TagName:Rew2CharacteristicTensionSpeedInfluence,TagValue: DB 93 DBW 30
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactOne).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_71 ,DisplayName:Pressure char. cont. roll rew.2 [d1][%],TagName:Rew2CharacteristicPressureContact_D01,TagValue:  DB 93 DBW 152
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactTwo).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_72 ,DisplayName:Pressure char. cont. roll rew.2 [d2][%],TagName:Rew2CharacteristicPressureContact_D02,TagValue:  DB 93 DBW 154
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactThree).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_73 ,DisplayName:Pressure char. cont. roll rew.2 [d3][%],TagName:Rew2CharacteristicPressureContact_D03,TagValue:  DB 93 DBW 156
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactFour).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_74 ,DisplayName:Pressure char. cont. roll rew.2 [d4][%],TagName:Rew2CharacteristicPressureContact_D04,TagValue:  DB 93 DBW 158
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactFive).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_75 ,DisplayName:Pressure char. cont. roll rew.2 [d5][%],TagName:Rew2CharacteristicPressureContact_D05,TagValue:  DB 93 DBW 160
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactSix).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_76 ,DisplayName:Pressure char. cont. roll rew.2 [d6][%],TagName:Rew2CharacteristicPressureContact_D06,TagValue:  DB 93 DBW 162
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactSeven).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_77 ,DisplayName:Pressure char. cont. roll rew.2 [d7][%],TagName:Rew2CharacteristicPressureContact_D07,TagValue:  DB 93 DBW 164
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactEight).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_78 ,DisplayName:Pressure char. cont. roll rew.2 [d8][%],TagName:Rew2CharacteristicPressureContact_D08,TagValue:  DB 93 DBW 166
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactNine).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_79 ,DisplayName:Pressure char. cont. roll rew.2 [d9][%],TagName:Rew2CharacteristicPressureContact_D09,TagValue:  DB 93 DBW 168
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactTen).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_80 ,DisplayName:Pressure char. cont. roll rew.2 [d10][%],TagName:Rew2CharacteristicPressureContact_D010,TagValue:  DB 93 DBW 170
            RuleFor(x => x.RewinderTwoCharacteristicPressureContactSpeedInfluence).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_81 ,DisplayName: Pressure char. cont. roll rew.2 speed[%],TagName:Rew2CharacteristicPressureContactSpeedInfluence,TagValue: DB 93 DBW 150
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportOne).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_82 ,DisplayName:Pressure char. supp. roll rew.2 [d1][%],TagName:Rew2CharacteristicPressureSupport_D01,TagValue:DB 93 DBW 212
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportTwo).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_83 ,DisplayName:Pressure char. supp. roll rew.2 [d2][%],TagName:Rew2CharacteristicPressureSupport_D02,TagValue:DB 93 DBW 214
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportThree).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_84 ,DisplayName:Pressure char. supp. roll rew.2 [d3][%],TagName:Rew2CharacteristicPressureSupport_D03,TagValue:DB 93 DBW 216
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportFour).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_85 ,DisplayName:Pressure char. supp. roll rew.2 [d4][%],TagName:Rew2CharacteristicPressureSupport_D04,TagValue:DB 93 DBW 218
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportFive).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_86 ,DisplayName:Pressure char. supp. roll rew.2 [d5][%],TagName:Rew2CharacteristicPressureSupport_D05,TagValue:DB 93 DBW 220
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportSix).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_87 ,DisplayName:Pressure char. supp. roll rew.2 [d6][%],TagName:Rew2CharacteristicPressureSupport_D06,TagValue:DB 93 DBW 222
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportSeven).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_88 ,DisplayName:Pressure char. supp. roll rew.2 [d7][%],TagName:Rew2CharacteristicPressureSupport_D07,TagValue:DB 93 DBW 224
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportEight).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_89 ,DisplayName:Pressure char. supp. roll rew.2 [d8][%],TagName:Rew2CharacteristicPressureSupport_D08,TagValue:DB 93 DBW 226
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportNine).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_90 ,DisplayName:Pressure char. supp. roll rew.2 [d9][%],TagName:Rew2CharacteristicPressureSupport_D09,TagValue:DB 93 DBW 228
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportTen).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_91 ,DisplayName:Pressure char. supp. roll rew.2 [d10][%],TagName:Rew2CharacteristicPressureSupport_D010,TagValue:DB 93 DBW 230
            RuleFor(x => x.RewinderTwoCharacteristicPressureSupportSpeedInfluence).InclusiveBetween(int.MinValue, int.MaxValue);//Name:Recipe_entry_0_92 ,DisplayName: Pressure char. supp. roll rew.2 speed[%],TagName:Rew2CharacteristicPressureSupportSpeedInfluence,TagValue:  DB 93 DBW 210
           
            RuleFor(x => x.Optime).NotEmpty();
            RuleFor(x => x.Optime).LessThanOrEqualTo(DateTime.Now);

            RuleFor(x => x.IsActive).NotEmpty();
            RuleFor(x => x.IsActive).InclusiveBetween(false, true);
        }
    }
}
